# Generated by Django 3.2.5 on 2021-08-25 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='todo',
            new_name='todo_model',
        ),
    ]
