# Generated by Django 3.2.5 on 2021-08-26 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_todo_todo_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='todo_model',
            new_name='todo',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='todo',
            new_name='title',
        ),
    ]
