# Generated by Django 3.2.6 on 2021-08-28 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 28, 12, 38, 7, 633928)),
        ),
    ]
