# Generated by Django 3.2.6 on 2021-08-28 09:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20210828_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 28, 9, 24, 35, 906701, tzinfo=utc)),
        ),
    ]
