# Generated by Django 3.2.6 on 2021-09-07 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_auto_20210907_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 7, 23, 52, 47, 468456)),
        ),
    ]
